[package]
name = "location"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.11"
axum-client-ip = "0.4.0"
axum-extra = { version = "0.7.1", features = ["typed-routing"] }
chrono = "0.4.24"
csv = "1.2.1"
hex = "0.4.3"
mime_guess = "2.0.4"
rust-embed = "6.6.0"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
zip = "0.6.4"

[profile.release]
strip = true
lto = true
